const express = require('express')
// const mongoose=require('mongoose')
const app = express()
const cors=require('cors')
const { userRouter } = require("./routes/user")
const { todoRouter } = require("./routes/todo")
const { mongoose } = require('mongoose')
const { mongoUrl } = require('./config')
const dotenv = require('dotenv')
require('dotenv').config()

app.use(express.json())
app.use(cors())
app.use('/user', userRouter)
app.use('/todo', todoRouter)
mongoose.connect(mongoUrl)
app.listen(3000)